graph TD
OTHER --> U:_foldersim_sim_apps_docs_next_config_ts
OTHER --> U:_foldersim_sim_apps_docs_proxy_ts
OTHER --> U:_foldersim_sim_apps_docs_source_config_ts
OTHER --> U:_foldersim_sim_apps_docs_app_layout_config_tsx
OTHER --> U:_foldersim_sim_apps_docs_app_layout_tsx
OTHER --> U:_foldersim_sim_apps_docs_app_llms-full_txt_route_ts
OTHER --> U:_foldersim_sim_apps_docs_app_llms_mdx_[[___slug]]_route_ts
OTHER --> U:_foldersim_sim_apps_docs_app_llms_txt_route_ts
OTHER --> U:_foldersim_sim_apps_docs_app_robots_txt_route_ts
OTHER --> U:_foldersim_sim_apps_docs_app_sitemap_xml_route_ts
OTHER --> U:_foldersim_sim_apps_docs_app_[lang]_layout_tsx
OTHER --> U:_foldersim_sim_apps_docs_app_[lang]_not-found_tsx
OTHER --> U:_foldersim_sim_apps_docs_app_[lang]_[[___slug]]_page_tsx
OTHER --> U:_foldersim_sim_apps_docs_components_icons_tsx
OTHER --> U:_foldersim_sim_apps_docs_components_page-actions_tsx
OTHER --> U:_foldersim_sim_apps_docs_components_structured-data_tsx
OTHER --> U:_foldersim_sim_apps_docs_components_docs-layout_page-navigation-arrows_tsx
OTHER --> U:_foldersim_sim_apps_docs_components_docs-layout_sidebar-components_tsx
OTHER --> U:_foldersim_sim_apps_docs_components_docs-layout_toc-footer_tsx
OTHER --> U:_foldersim_sim_apps_docs_components_navbar_navbar_tsx
OTHER --> U:_foldersim_sim_apps_docs_components_ui_block-info-card_tsx
OTHER --> U:_foldersim_sim_apps_docs_components_ui_button_tsx
OTHER --> U:_foldersim_sim_apps_docs_components_ui_code-block_tsx
OTHER --> U:_foldersim_sim_apps_docs_components_ui_heading_tsx
OTHER --> U:_foldersim_sim_apps_docs_components_ui_icon-mapping_ts
OTHER --> U:_foldersim_sim_apps_docs_components_ui_image_tsx
OTHER --> U:_foldersim_sim_apps_docs_components_ui_language-dropdown_tsx
OTHER --> U:_foldersim_sim_apps_docs_components_ui_lightbox_tsx
OTHER --> U:_foldersim_sim_apps_docs_components_ui_search-trigger_tsx
OTHER --> U:_foldersim_sim_apps_docs_components_ui_theme-toggle_tsx
OTHER --> U:_foldersim_sim_apps_docs_components_ui_video_tsx
OTHER --> U:_foldersim_sim_apps_docs_lib_cn_ts
OTHER --> U:_foldersim_sim_apps_docs_lib_i18n_ts
OTHER --> U:_foldersim_sim_apps_docs_lib_llms_ts
OTHER --> U:_foldersim_sim_apps_docs_lib_source_ts
OTHER --> U:_foldersim_sim_apps_docs_lib_utils_ts
OTHER --> U:_foldersim_sim_apps_sim_drizzle_config_ts
OTHER --> U:_foldersim_sim_apps_sim_instrumentation-client_ts
OTHER --> U:_foldersim_sim_apps_sim_instrumentation-edge_ts
OTHER --> U:_foldersim_sim_apps_sim_instrumentation-node_ts
OTHER --> U:_foldersim_sim_apps_sim_instrumentation_ts
OTHER --> U:_foldersim_sim_apps_sim_next_config_ts
OTHER --> U:_foldersim_sim_apps_sim_proxy_ts
OTHER --> U:_foldersim_sim_apps_sim_tailwind_config_ts
OTHER --> U:_foldersim_sim_apps_sim_telemetry_config_ts
OTHER --> U:_foldersim_sim_apps_sim_trigger_config_ts
OTHER --> U:_foldersim_sim_apps_sim_vitest_config_ts
OTHER --> U:_foldersim_sim_apps_sim_vitest_setup_ts
OTHER --> U:_foldersim_sim_apps_sim_app_global-error_tsx
OTHER --> U:_foldersim_sim_apps_sim_app_layout_tsx
API --> U:_foldersim_sim_apps_docs_app_api_og_route_tsx
API --> U:_foldersim_sim_apps_docs_app_api_search_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_accounts_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_forget-password_route_test_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_forget-password_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_oauth_utils_test_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_oauth_utils_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_oauth_connections_route_test_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_oauth_connections_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_oauth_credentials_route_test_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_oauth_credentials_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_oauth_disconnect_route_test_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_oauth_disconnect_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_oauth_microsoft_file_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_oauth_microsoft_files_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_oauth_token_route_test_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_oauth_token_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_oauth_wealthbox_item_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_oauth_wealthbox_items_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_oauth2_callback_shopify_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_oauth2_shopify_store_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_reset-password_route_test_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_reset-password_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_shopify_authorize_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_socket-token_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_sso_providers_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_sso_register_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_trello_authorize_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_trello_callback_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_trello_store_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_webhook_stripe_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_auth_[___all]_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_billing_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_billing_credits_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_billing_portal_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_billing_update-cost_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_careers_submit_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_chat_route_test_ts
API --> U:_foldersim_sim_apps_sim_app_api_chat_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_chat_utils_test_ts
API --> U:_foldersim_sim_apps_sim_app_api_chat_utils_ts
API --> U:_foldersim_sim_apps_sim_app_api_chat_manage_[id]_route_test_ts
API --> U:_foldersim_sim_apps_sim_app_api_chat_manage_[id]_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_chat_validate_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_chat_[identifier]_route_test_ts
API --> U:_foldersim_sim_apps_sim_app_api_chat_[identifier]_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_chat_[identifier]_otp_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_copilot_api-keys_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_copilot_api-keys_generate_route_ts
API --> U:_foldersim_sim_apps_sim_app_api_copilot_api-keys_validate_route_ts
DATA --> U:_foldersim_sim_apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_copilot_components_copilot-message_hooks_use-message-feedback_ts
DATA --> U:_foldersim_sim_apps_sim_blocks_blocks_dynamodb_ts
DATA --> U:_foldersim_sim_apps_sim_blocks_blocks_mongodb_ts
DATA --> U:_foldersim_sim_apps_sim_blocks_blocks_sharepoint_ts
DATA --> U:_foldersim_sim_apps_sim_lib_core_rate-limiter_storage_db-token-bucket_ts
DATA --> U:_foldersim_sim_apps_sim_tools_dynamodb_delete_ts
DATA --> U:_foldersim_sim_apps_sim_tools_dynamodb_get_ts
DATA --> U:_foldersim_sim_apps_sim_tools_dynamodb_index_ts
DATA --> U:_foldersim_sim_apps_sim_tools_dynamodb_put_ts
DATA --> U:_foldersim_sim_apps_sim_tools_dynamodb_query_ts
DATA --> U:_foldersim_sim_apps_sim_tools_dynamodb_scan_ts
DATA --> U:_foldersim_sim_apps_sim_tools_dynamodb_types_ts
DATA --> U:_foldersim_sim_apps_sim_tools_dynamodb_update_ts
DATA --> U:_foldersim_sim_apps_sim_tools_github_repo_info_ts
DATA --> U:_foldersim_sim_apps_sim_tools_mailchimp_get_campaign_report_ts
DATA --> U:_foldersim_sim_apps_sim_tools_mailchimp_get_campaign_reports_ts
DATA --> U:_foldersim_sim_apps_sim_tools_mongodb_delete_ts
DATA --> U:_foldersim_sim_apps_sim_tools_mongodb_execute_ts
DATA --> U:_foldersim_sim_apps_sim_tools_mongodb_index_ts
DATA --> U:_foldersim_sim_apps_sim_tools_mongodb_insert_ts
DATA --> U:_foldersim_sim_apps_sim_tools_mongodb_query_ts
DATA --> U:_foldersim_sim_apps_sim_tools_mongodb_types_ts
DATA --> U:_foldersim_sim_apps_sim_tools_mongodb_update_ts
DATA --> U:_foldersim_sim_apps_sim_tools_salesforce_get_report_ts
DATA --> U:_foldersim_sim_apps_sim_tools_salesforce_list_reports_ts
DATA --> U:_foldersim_sim_apps_sim_tools_salesforce_list_report_types_ts
DATA --> U:_foldersim_sim_apps_sim_tools_salesforce_run_report_ts
DATA --> U:_foldersim_sim_apps_sim_tools_sharepoint_add_list_items_ts
DATA --> U:_foldersim_sim_apps_sim_tools_sharepoint_create_list_ts
DATA --> U:_foldersim_sim_apps_sim_tools_sharepoint_create_page_ts
DATA --> U:_foldersim_sim_apps_sim_tools_sharepoint_get_list_ts
DATA --> U:_foldersim_sim_apps_sim_tools_sharepoint_index_ts
DATA --> U:_foldersim_sim_apps_sim_tools_sharepoint_list_sites_ts
DATA --> U:_foldersim_sim_apps_sim_tools_sharepoint_read_page_ts
DATA --> U:_foldersim_sim_apps_sim_tools_sharepoint_types_ts
DATA --> U:_foldersim_sim_apps_sim_tools_sharepoint_update_list_ts
DATA --> U:_foldersim_sim_apps_sim_tools_sharepoint_upload_file_ts
DATA --> U:_foldersim_sim_apps_sim_tools_sharepoint_utils_ts
DATA --> U:_foldersim_sim_packages_db_constants_ts
DATA --> U:_foldersim_sim_packages_db_drizzle_config_ts
DATA --> U:_foldersim_sim_packages_db_index_ts
DATA --> U:_foldersim_sim_packages_db_schema_ts
DATA --> U:_foldersim_sim_packages_db_scripts_deregister-sso-provider_ts
DATA --> U:_foldersim_sim_packages_db_scripts_migrate-deployment-versions_ts
DATA --> U:_foldersim_sim_packages_db_scripts_register-sso-provider_ts
SERVICE --> U:_foldersim_sim_apps_sim_blocks_blocks_servicenow_ts
SERVICE --> U:_foldersim_sim_apps_sim_lib_core_idempotency_service_ts
SERVICE --> U:_foldersim_sim_apps_sim_lib_knowledge_service_ts
SERVICE --> U:_foldersim_sim_apps_sim_lib_knowledge_chunks_service_ts
SERVICE --> U:_foldersim_sim_apps_sim_lib_knowledge_documents_service_ts
SERVICE --> U:_foldersim_sim_apps_sim_lib_knowledge_tags_service_ts
SERVICE --> U:_foldersim_sim_apps_sim_lib_logs_execution_snapshot_service_test_ts
SERVICE --> U:_foldersim_sim_apps_sim_lib_logs_execution_snapshot_service_ts
SERVICE --> U:_foldersim_sim_apps_sim_lib_mcp_service_ts
SERVICE --> U:_foldersim_sim_apps_sim_lib_messaging_sms_service_ts
SERVICE --> U:_foldersim_sim_apps_sim_lib_uploads_core_storage-service_ts
SERVICE --> U:_foldersim_sim_apps_sim_lib_webhooks_gmail-polling-service_ts
SERVICE --> U:_foldersim_sim_apps_sim_lib_webhooks_outlook-polling-service_ts
SERVICE --> U:_foldersim_sim_apps_sim_lib_webhooks_rss-polling-service_ts
SERVICE --> U:_foldersim_sim_apps_sim_tools_servicenow_create_record_ts
SERVICE --> U:_foldersim_sim_apps_sim_tools_servicenow_delete_record_ts
SERVICE --> U:_foldersim_sim_apps_sim_tools_servicenow_index_ts
SERVICE --> U:_foldersim_sim_apps_sim_tools_servicenow_read_record_ts
SERVICE --> U:_foldersim_sim_apps_sim_tools_servicenow_types_ts
SERVICE --> U:_foldersim_sim_apps_sim_tools_servicenow_update_record_ts
SERVICE --> U:_foldersim_sim_apps_sim_tools_servicenow_utils_ts