graph TD
apps_docs_lib_utils_ts[utils.ts]
apps_sim_app_api_files_utils_ts[utils.ts]
apps_sim_app_api_tools_sqs_utils_ts[utils.ts]
apps_sim_app_api_workflows_utils_ts[utils.ts]
apps_sim_app_workspace_[workspaceId]_logs_utils_ts[utils.ts]
apps_sim_app_workspace_[workspaceId]_utils_commands-utils_ts[commands-utils.ts]
apps_sim_app_workspace_[workspaceId]_w_utils_get-user-color_ts[get-user-color.ts]
apps_sim_app_workspace_[workspaceId]_w_[workflowId]_utils_block-ring-utils_ts[block-ring-utils.ts]
apps_sim_app_workspace_[workspaceId]_w_[workflowId]_utils_index_ts[index.ts]
apps_sim_blocks_utils_ts[utils.ts]
apps_sim_executor_utils_test_ts[utils.test.ts]
apps_sim_executor_utils_ts[utils.ts]
apps_sim_executor_human-in-the-loop_utils_ts[utils.ts]
apps_sim_executor_utils_block-data_ts[block-data.ts]
apps_sim_executor_utils_connections_ts[connections.ts]
apps_sim_executor_utils_json_ts[json.ts]
apps_sim_executor_utils_reference-validation_ts[reference-validation.ts]
apps_sim_executor_utils_start-block_ts[start-block.ts]
apps_sim_executor_utils_subflow-utils_ts[subflow-utils.ts]
apps_sim_executor___test-utils___test-executor_ts[test-executor.ts]
apps_sim_hooks_queries_utils_index_ts[index.ts]
apps_sim_lib_billing_client_utils_ts[utils.ts]
apps_sim_lib_billing_subscriptions_utils_ts[utils.ts]
apps_sim_lib_copilot_utils_ts[utils.ts]
apps_sim_lib_core_utils_browser-storage_ts[browser-storage.ts]
apps_sim_lib_core_utils_cn_ts[cn.ts]
apps_sim_lib_core_utils_display-filters_ts[display-filters.ts]
apps_sim_lib_core_utils_formatting_ts[formatting.ts]
apps_sim_lib_core_utils_request_ts[request.ts]
apps_sim_lib_core_utils_response-format_ts[response-format.ts]
apps_sim_lib_core_utils_scheduling_ts[scheduling.ts]
apps_sim_lib_core_utils_sse_ts[sse.ts]
apps_sim_lib_core_utils_validation_ts[validation.ts]
apps_sim_lib_file-parsers_utils_ts[utils.ts]
apps_sim_lib_knowledge_tags_utils_ts[utils.ts]
apps_sim_lib_messaging_email_utils_test_ts[utils.test.ts]
apps_sim_lib_messaging_email_utils_ts[utils.ts]
apps_sim_lib_uploads_utils_index_ts[index.ts]
apps_sim_lib_uploads_utils_validation_ts[validation.ts]
apps_sim_lib_webhooks_provider-utils_ts[provider-utils.ts]
apps_sim_lib_webhooks_utils_ts[utils.ts]
apps_sim_lib_workflows_input-format-utils_ts[input-format-utils.ts]
apps_sim_lib_workflows_operations_deployment-utils_ts[deployment-utils.ts]
apps_sim_lib_workflows_schedules_utils_test_ts[utils.test.ts]
apps_sim_lib_workflows_schedules_utils_ts[utils.ts]
apps_sim_lib_workflows_triggers_trigger-utils_ts[trigger-utils.ts]
apps_sim_lib_workspaces_organization_utils_ts[utils.ts]
apps_sim_providers_anthropic_utils_ts[utils.ts]
apps_sim_providers_cerebras_utils_ts[utils.ts]
apps_sim_providers_deepseek_utils_ts[utils.ts]
utils_grp[UTILS Layer Chunk 1]
utils_grp --> apps_docs_lib_utils_ts
utils_grp --> apps_sim_app_api_files_utils_ts
utils_grp --> apps_sim_app_api_tools_sqs_utils_ts
utils_grp --> apps_sim_app_api_workflows_utils_ts
utils_grp --> apps_sim_app_workspace_[workspaceId]_logs_utils_ts
utils_grp --> apps_sim_app_workspace_[workspaceId]_utils_commands-utils_ts
utils_grp --> apps_sim_app_workspace_[workspaceId]_w_utils_get-user-color_ts
utils_grp --> apps_sim_app_workspace_[workspaceId]_w_[workflowId]_utils_block-ring-utils_ts
utils_grp --> apps_sim_app_workspace_[workspaceId]_w_[workflowId]_utils_index_ts
utils_grp --> apps_sim_blocks_utils_ts
utils_grp --> apps_sim_executor_utils_test_ts
utils_grp --> apps_sim_executor_utils_ts
utils_grp --> apps_sim_executor_human-in-the-loop_utils_ts
utils_grp --> apps_sim_executor_utils_block-data_ts
utils_grp --> apps_sim_executor_utils_connections_ts
utils_grp --> apps_sim_executor_utils_json_ts
utils_grp --> apps_sim_executor_utils_reference-validation_ts
utils_grp --> apps_sim_executor_utils_start-block_ts
utils_grp --> apps_sim_executor_utils_subflow-utils_ts
utils_grp --> apps_sim_executor___test-utils___test-executor_ts
utils_grp --> apps_sim_hooks_queries_utils_index_ts
utils_grp --> apps_sim_lib_billing_client_utils_ts
utils_grp --> apps_sim_lib_billing_subscriptions_utils_ts
utils_grp --> apps_sim_lib_copilot_utils_ts
utils_grp --> apps_sim_lib_core_utils_browser-storage_ts
utils_grp --> apps_sim_lib_core_utils_cn_ts
utils_grp --> apps_sim_lib_core_utils_display-filters_ts
utils_grp --> apps_sim_lib_core_utils_formatting_ts
utils_grp --> apps_sim_lib_core_utils_request_ts
utils_grp --> apps_sim_lib_core_utils_response-format_ts
utils_grp --> apps_sim_lib_core_utils_scheduling_ts
utils_grp --> apps_sim_lib_core_utils_sse_ts
utils_grp --> apps_sim_lib_core_utils_validation_ts
utils_grp --> apps_sim_lib_file-parsers_utils_ts
utils_grp --> apps_sim_lib_knowledge_tags_utils_ts
utils_grp --> apps_sim_lib_messaging_email_utils_test_ts
utils_grp --> apps_sim_lib_messaging_email_utils_ts
utils_grp --> apps_sim_lib_uploads_utils_index_ts
utils_grp --> apps_sim_lib_uploads_utils_validation_ts
utils_grp --> apps_sim_lib_webhooks_provider-utils_ts
utils_grp --> apps_sim_lib_webhooks_utils_ts
utils_grp --> apps_sim_lib_workflows_input-format-utils_ts
utils_grp --> apps_sim_lib_workflows_operations_deployment-utils_ts
utils_grp --> apps_sim_lib_workflows_schedules_utils_test_ts
utils_grp --> apps_sim_lib_workflows_schedules_utils_ts
utils_grp --> apps_sim_lib_workflows_triggers_trigger-utils_ts
utils_grp --> apps_sim_lib_workspaces_organization_utils_ts
utils_grp --> apps_sim_providers_anthropic_utils_ts
utils_grp --> apps_sim_providers_cerebras_utils_ts
utils_grp --> apps_sim_providers_deepseek_utils_ts