graph TD
apps_docs_next_config_ts[next.config.ts]
apps_docs_proxy_ts[proxy.ts]
apps_docs_source_config_ts[source.config.ts]
apps_docs_app_api_search_route_ts[route.ts]
apps_docs_app_llms-full_txt_route_ts[route.ts]
apps_docs_app_llms_mdx_[[___slug]]_route_ts[route.ts]
apps_docs_lib_cn_ts[cn.ts]
apps_docs_lib_i18n_ts[i18n.ts]
apps_docs_lib_llms_ts[llms.ts]
apps_docs_lib_source_ts[source.ts]
apps_sim_instrumentation-edge_ts[instrumentation-edge.ts]
apps_sim_instrumentation_ts[instrumentation.ts]
apps_sim_tailwind_config_ts[tailwind.config.ts]
apps_sim_trigger_config_ts[trigger.config.ts]
apps_sim_vitest_config_ts[vitest.config.ts]
apps_sim_app_manifest_ts[manifest.ts]
apps_sim_app_(landing)_components_index_ts[index.ts]
apps_sim_app_(landing)_components_footer_consts_ts[consts.ts]
apps_sim_app_(landing)_components_footer_components_index_ts[index.ts]
apps_sim_app_(landing)_components_hero_components_index_ts[index.ts]
apps_sim_app_api_careers_submit_route_ts[route.ts]
apps_sim_app_api_copilot_methods_route_test_ts[route.test.ts]
apps_sim_app_api_providers_base_models_route_ts[route.ts]
apps_sim_app_api_tools_postgresql_delete_route_ts[route.ts]
apps_sim_app_api_tools_rds_delete_route_ts[route.ts]
apps_sim_app_api_tools_sqs_send_route_ts[route.ts]
apps_sim_app_api_tools_ssh_check-command-exists_route_ts[route.ts]
apps_sim_app_api_tools_ssh_move-rename_route_ts[route.ts]
apps_sim_app_api_tools_ssh_read-file-content_route_ts[route.ts]
apps_sim_app_api_tools_ssh_upload-file_route_ts[route.ts]
apps_sim_app_api_tools_stagehand_agent_route_ts[route.ts]
apps_sim_app_api_tools_stagehand_extract_route_ts[route.ts]
apps_sim_app_api_tools_thinking_route_ts[route.ts]
apps_sim_app_api_v1_logs_meta_ts[meta.ts]
apps_sim_app_api_workspaces_[id]_notifications_constants_ts[constants.ts]
apps_sim_app_api_yaml_autolayout_route_ts[route.ts]
apps_sim_app_chat_hooks_index_ts[index.ts]
apps_sim_app_invite_components_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_knowledge_components_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_knowledge_[id]_components_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_knowledge_[id]_[documentId]_components_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_logs_types_ts[types.ts]
apps_sim_app_workspace_[workspaceId]_logs_components_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_logs_components_dashboard_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_logs_components_dashboard_components_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_logs_components_dashboard_components_line-chart_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_logs_components_dashboard_components_status-bar_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_logs_components_dashboard_components_workflows-list_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_logs_components_log-details_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_logs_components_log-details_components_file-download_index_ts[index.ts]
application_grp[APPLICATION Layer Chunk 1]
application_grp --> apps_docs_next_config_ts
application_grp --> apps_docs_proxy_ts
application_grp --> apps_docs_source_config_ts
application_grp --> apps_docs_app_api_search_route_ts
application_grp --> apps_docs_app_llms-full_txt_route_ts
application_grp --> apps_docs_app_llms_mdx_[[___slug]]_route_ts
application_grp --> apps_docs_lib_cn_ts
application_grp --> apps_docs_lib_i18n_ts
application_grp --> apps_docs_lib_llms_ts
application_grp --> apps_docs_lib_source_ts
application_grp --> apps_sim_instrumentation-edge_ts
application_grp --> apps_sim_instrumentation_ts
application_grp --> apps_sim_tailwind_config_ts
application_grp --> apps_sim_trigger_config_ts
application_grp --> apps_sim_vitest_config_ts
application_grp --> apps_sim_app_manifest_ts
application_grp --> apps_sim_app_(landing)_components_index_ts
application_grp --> apps_sim_app_(landing)_components_footer_consts_ts
application_grp --> apps_sim_app_(landing)_components_footer_components_index_ts
application_grp --> apps_sim_app_(landing)_components_hero_components_index_ts
application_grp --> apps_sim_app_api_careers_submit_route_ts
application_grp --> apps_sim_app_api_copilot_methods_route_test_ts
application_grp --> apps_sim_app_api_providers_base_models_route_ts
application_grp --> apps_sim_app_api_tools_postgresql_delete_route_ts
application_grp --> apps_sim_app_api_tools_rds_delete_route_ts
application_grp --> apps_sim_app_api_tools_sqs_send_route_ts
application_grp --> apps_sim_app_api_tools_ssh_check-command-exists_route_ts
application_grp --> apps_sim_app_api_tools_ssh_move-rename_route_ts
application_grp --> apps_sim_app_api_tools_ssh_read-file-content_route_ts
application_grp --> apps_sim_app_api_tools_ssh_upload-file_route_ts
application_grp --> apps_sim_app_api_tools_stagehand_agent_route_ts
application_grp --> apps_sim_app_api_tools_stagehand_extract_route_ts
application_grp --> apps_sim_app_api_tools_thinking_route_ts
application_grp --> apps_sim_app_api_v1_logs_meta_ts
application_grp --> apps_sim_app_api_workspaces_[id]_notifications_constants_ts
application_grp --> apps_sim_app_api_yaml_autolayout_route_ts
application_grp --> apps_sim_app_chat_hooks_index_ts
application_grp --> apps_sim_app_invite_components_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_knowledge_components_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_knowledge_[id]_components_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_knowledge_[id]_[documentId]_components_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_logs_types_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_logs_components_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_logs_components_dashboard_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_logs_components_dashboard_components_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_logs_components_dashboard_components_line-chart_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_logs_components_dashboard_components_status-bar_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_logs_components_dashboard_components_workflows-list_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_logs_components_log-details_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_logs_components_log-details_components_file-download_index_ts
apps_sim_app_workspace_[workspaceId]_logs_components_log-details_components_frozen-canvas_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_logs_components_log-details_components_trace-spans_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_logs_components_logs-toolbar_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_logs_components_logs-toolbar_components_controls_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_logs_components_logs-toolbar_components_notifications_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_logs_components_logs-toolbar_components_notifications_components_slack-channel-selector_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_logs_components_logs-toolbar_components_notifications_components_workflow-selector_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_logs_components_logs-toolbar_components_search_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_logs_hooks_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_logs_hooks_use-log-details-resize_ts[use-log-details-resize.ts]
apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_settings-modal_components_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_settings-modal_components_mcp_components_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_settings-modal_components_mcp_components_types_ts[types.ts]
apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_settings-modal_components_subscription_plan-configs_ts[plan-configs.ts]
apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_settings-modal_components_subscription_subscription-permissions_ts[subscription-permissions.ts]
apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_settings-modal_components_subscription_components_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_settings-modal_components_subscription_components_cancel-subscription_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_settings-modal_components_subscription_components_cost-breakdown_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_settings-modal_components_subscription_components_credit-balance_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_settings-modal_components_subscription_components_plan-card_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_settings-modal_components_subscription_components_usage-limit_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_settings-modal_components_team-management_components_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_workflow-list_components_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_workspace-header_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_workspace-header_components_invite-modal_components_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_workspace-header_components_invite-modal_components_types_ts[types.ts]
apps_sim_app_workspace_[workspaceId]_w_components_sidebar_hooks_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_components_sidebar_hooks_use-folder-expand_ts[use-folder-expand.ts]
apps_sim_app_workspace_[workspaceId]_w_components_sidebar_hooks_use-item-drag_ts[use-item-drag.ts]
apps_sim_app_workspace_[workspaceId]_w_components_sidebar_hooks_use-workflow-selection_ts[use-workflow-selection.ts]
apps_sim_app_workspace_[workspaceId]_w_hooks_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_hooks_use-can-delete_ts[use-can-delete.ts]
apps_sim_app_workspace_[workspaceId]_w_hooks_use-delete-folder_ts[use-delete-folder.ts]
apps_sim_app_workspace_[workspaceId]_w_hooks_use-duplicate-folder_ts[use-duplicate-folder.ts]
apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_chat_components_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_chat_hooks_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_copilot_components_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_copilot_components_copilot-message_components_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_copilot_components_copilot-message_hooks_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_copilot_components_user-input_constants_ts[constants.ts]
apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_copilot_components_user-input_components_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_copilot_hooks_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_deploy_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_deploy_components_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_deploy_components_deploy-modal_components_general_components_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_deploy_hooks_index_ts[index.ts]
apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_editor_components_index_ts[index.ts]
application_grp[APPLICATION Layer Chunk 2]
application_grp --> apps_sim_app_workspace_[workspaceId]_logs_components_log-details_components_frozen-canvas_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_logs_components_log-details_components_trace-spans_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_logs_components_logs-toolbar_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_logs_components_logs-toolbar_components_controls_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_logs_components_logs-toolbar_components_notifications_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_logs_components_logs-toolbar_components_notifications_components_slack-channel-selector_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_logs_components_logs-toolbar_components_notifications_components_workflow-selector_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_logs_components_logs-toolbar_components_search_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_logs_hooks_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_logs_hooks_use-log-details-resize_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_settings-modal_components_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_settings-modal_components_mcp_components_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_settings-modal_components_mcp_components_types_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_settings-modal_components_subscription_plan-configs_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_settings-modal_components_subscription_subscription-permissions_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_settings-modal_components_subscription_components_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_settings-modal_components_subscription_components_cancel-subscription_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_settings-modal_components_subscription_components_cost-breakdown_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_settings-modal_components_subscription_components_credit-balance_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_settings-modal_components_subscription_components_plan-card_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_settings-modal_components_subscription_components_usage-limit_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_settings-modal_components_team-management_components_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_workflow-list_components_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_workspace-header_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_workspace-header_components_invite-modal_components_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_components_sidebar_components_workspace-header_components_invite-modal_components_types_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_components_sidebar_hooks_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_components_sidebar_hooks_use-folder-expand_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_components_sidebar_hooks_use-item-drag_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_components_sidebar_hooks_use-workflow-selection_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_hooks_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_hooks_use-can-delete_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_hooks_use-delete-folder_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_hooks_use-duplicate-folder_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_chat_components_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_chat_hooks_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_copilot_components_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_copilot_components_copilot-message_components_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_copilot_components_copilot-message_hooks_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_copilot_components_user-input_constants_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_copilot_components_user-input_components_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_copilot_hooks_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_deploy_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_deploy_components_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_deploy_components_deploy-modal_components_general_components_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_deploy_hooks_index_ts
application_grp --> apps_sim_app_workspace_[workspaceId]_w_[workflowId]_components_panel_components_editor_components_index_ts